# Generated by Django 5.0.6 on 2024-07-18 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Equipment", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categories",
            name="category_code",
        ),
        migrations.RemoveField(
            model_name="subcategories",
            name="subCat_code",
        ),
    ]
