# Generated by Django 5.0.6 on 2024-07-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Equipment", "0002_remove_categories_category_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="companyExperts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expertFistName", models.CharField(max_length=100)),
                ("expertLastName", models.CharField(max_length=150)),
                ("expertMobile", models.BigIntegerField()),
                ("expertcompany", models.CharField(max_length=150)),
            ],
            options={
                "verbose_name": "کارشناسان",
                "verbose_name_plural": " 4. کارشناسان شرکت ها",
            },
        ),
    ]
