# Generated by Django 5.0.6 on 2024-07-21 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Equipment", "0003_companyexperts"),
    ]

    operations = [
        migrations.CreateModel(
            name="supportCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("companyName", models.CharField(max_length=100)),
                ("companyPhon1", models.CharField(max_length=13)),
                ("companyPhon2", models.CharField(blank=True, max_length=13)),
                ("companyPhon3", models.CharField(blank=True, max_length=13)),
                ("companyRank", models.CharField(blank=True, max_length=50)),
                ("companyPhoneMobile", models.CharField(blank=True, max_length=13)),
            ],
            options={
                "verbose_name": "شرکت",
                "verbose_name_plural": "6.  شرکت ها",
            },
        ),
        migrations.AlterModelOptions(
            name="companyexperts",
            options={
                "verbose_name": "کارشناسان",
                "verbose_name_plural": "5. کارشناسان شرکت ها",
            },
        ),
        migrations.AlterField(
            model_name="companyexperts",
            name="expertMobile",
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name="companyexperts",
            name="expertcompany",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="Equipment.supportcompany",
            ),
        ),
    ]
