# Generated by Django 5.0.6 on 2024-07-21 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Equipment", "0004_supportcompany_alter_companyexperts_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="manufacturers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manufName", models.CharField(max_length=100)),
                ("manufAgency", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "سازنده محصول",
                "verbose_name_plural": "7. کارخانه سازنده محصول",
            },
        ),
        migrations.CreateModel(
            name="hardEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hardAssetNumber", models.IntegerField()),
                ("hardModel", models.CharField(max_length=50)),
                ("hardSerial", models.CharField(max_length=50)),
                ("hardFanavariNumber", models.IntegerField()),
                ("hardDesciption", models.CharField(max_length=300)),
                ("hardSize", models.CharField(max_length=50)),
                (
                    "hardBranch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Equipment.branch",
                    ),
                ),
                (
                    "hardName",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Equipment.subcategories",
                    ),
                ),
                (
                    "hardSupportCo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Equipment.supportcompany",
                    ),
                ),
                (
                    "hardManufacturer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Equipment.manufacturers",
                    ),
                ),
            ],
            options={
                "verbose_name": "سخت افزار",
                "verbose_name_plural": "8. سخت افزار",
            },
        ),
    ]
