# Generated by Django 5.0.6 on 2024-07-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Equipment", "0005_manufacturers_hardequipment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supportcompany",
            options={"verbose_name": "شرکت", "verbose_name_plural": "6.  شرکت پشتیبان"},
        ),
        migrations.AddField(
            model_name="subcategories",
            name="subCat_model",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="hardequipment",
            name="hardDesciption",
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
