# Generated by Django 5.0.6 on 2024-07-23 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Equipment", "0006_alter_supportcompany_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hardequipment",
            name="hardSupportCo",
        ),
        migrations.AddField(
            model_name="subcategories",
            name="subCat_SupportCo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Equipment.supportcompany",
            ),
        ),
    ]
