# Generated by Django 5.0.6 on 2024-07-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Equipment", "0008_supportcompany_companyceoname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="category_name",
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
