# Generated by Django 5.0.6 on 2024-07-23 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Equipment", "0009_alter_categories_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategories",
            name="subCat_manufacture",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="Equipment.manufacturers",
            ),
        ),
    ]
