# Generated by Django 5.0.6 on 2024-08-06 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Equipment", "0011_alter_companyexperts_expertmobile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturers",
            name="manufName",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
